### ISSUE TITLE
Improve e2e running locally

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_k8s#202]
I may not know the bazel kungfu to override the cluster name frankly.  So to run e2e locally, it is a bit hacky as you have to edit WORKSPACE file.  Also it is forcing Linux or a container, but it does not have support to run the container easily.

**Comment by nlopezgi** [comment]
I think a first good step would be to document how to run this from an arbitrary dev environment, and then to produce better error messages if tests cannot run properly.
iiuc, the e2e tests are currently setup to run with a specific cluster/namespace
Internally, we have a doc that @erain produced that explains how to set up the gcloud/docker/kubectl authentication/config to have this work properly.

We could start by creating an equivalent external doc that explains how to do this setup for an external user (i.e., a user that does not have access to our cluster/namespaces). Do you think you could start creating such a doc @chrislovecnm ? 
We could then add some additional validations in the e2e test scripts (e.g., not sure if possible, but test should check the namespace $USER exists or error out early otherwise).

wrt this forcing Linux or a container, I'm not sure what alternative there is. We should probably document how to run e2e tests inside of a container. We could make this part of the doc that explains how to do the setup for e2e tests. I imagine it should be feasible to use our bazel-docker-gcloud container (https://github.com/bazelbuild/bazel-toolchains/blob/master/container/ubuntu16_04/builders/bazel_docker_gcloud/BUILD), if not, we can change the container so that it will work.
We can also consider moving the e2e tests to always run inside a container, might be a bit more work but would make it trivial to run from almost any env.

**Comment by fejta** [comment]
minikube rule existed
