### ISSUE TITLE
How to properly pass arbitrary args to kubectl command.

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/rules_k8s#209]
Hi everyone,
@chrislovecnm @Globegitter @omadawn 
we already have 3 PRs in flight adding similar functionality:
https://github.com/bazelbuild/rules_k8s/pull/174 - Add arbitrary commands
https://github.com/bazelbuild/rules_k8s/pull/207 - Add command specific arguments
https://github.com/bazelbuild/rules_k8s/pull/198 - Adding capability to pass in args parameter to kubectl

Lets try to have a single discussion here about what we really need for this feature before spending too much time in the individual PRs.

iiuc there are some open issues in all these PRs:
A - Whether to use 1) args / $@ or 2) kubectl_args / %{kubectl_args} to pass values / replace them in the template
B - The location of the args once resolved in the kubectl call
C - How to test this w/o replicating the whole kitchen sink of e2e test files
D - Who should continue working on this feature request moving forward (to avoid duplicate effort)

If I'm missing any other open issues please let me know.
Now as for my opinions:
A - I initially thought option 2 was the one we should use, but after reading recent comments it seems option 1 is the preferred alternative to pass arguments to templates invoked via bazel run
B - I have no opinion on this as I dont know enough about tradeoffs
C - lets try to add tests that use this functionality without replicating the e2e scripts. I'll work with whomever continues working on this request
D - I dont have any strong opinions as to who should continue working on this feature

Happy to hear other folks thoughts
Also looping in @erain and @fejta

**Comment by Globegitter** [comment]
Thanks for pulling this together in a single issue @nlopezgi I think that makes total sense to unify the efforts here as I think we all want very similar things.

So I would vote to use `args` to follow bazel convention and so far I do not see any drawback of having the `$@` behind the subcommands (so e.g. `kubectl apply $@`) so I would also vote for that. But what are the other people's thoughts?

**Comment by Globegitter** [comment]
@chrislovecnm I am answering to your comment https://github.com/bazelbuild/rules_k8s/pull/207#issuecomment-433461535 here. The `$@` is necessary to be able to make use of `bazel run :target.apply -- --my-flag`, this is already used in a bunch of other bazel built scripts to allow for this. Otherwise I have no preference on how to proceed and who implements what - as @nlopezgi said though I think it does make sense to unify here and do not duplicate efforts any further :)

**Comment by chrislovecnm** [comment]
So million dollar question.  Can I override:

https://github.com/bazelbuild/rules_k8s/blob/e903ac6833b994e874728bba16cc7e23315ae690/examples/hellohttp/java/BUILD#L30-L38

From the command line?

For instance `bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 --define cluster=gke_chlove-57705_us-west1-b_staging-cloud-cluster --define repo=gcr.io/chlove-57705 //pyrios-ui:k8s.apply `

Can I get a cli switch that is built into bazel to override the value in `kubectl_args`.

I think we need an interface for this as well ...

**Comment by chrislovecnm** [comment]
>  is it not also possible to pass e.g. kubectl apply -v 10? Or more generically, are there any global flags that do not work after the command also?

I have not tested them. Have you?

If that is the case then I think our design gets simpler.

**Comment by chrislovecnm** [comment]
@Globegitter ^

**Comment by Globegitter** [comment]
@chrislovecnm yep at least the options I have tried are working.
E.g.

```
 kubectl apply --v 10 --alsologtostderr=true --stderrthreshold=1 -f test.yaml 
I1029 21:42:06.844441   12637 loader.go:359] Config loaded from file /home/markus/.kube/config
I1029 21:42:06.847416   12637 loader.go:359] Config loaded from file /home/markus/.kube/config
...
```

The same when using the `create` command. I also tested the `--cluster` flag. So it seems we can go with a simpler design here and just add the flags after the subcommand.

**Comment by omadawn** [comment]
I have found that generally you can place global arguments anywhere. 

This _might_ break in the future. Only recently have I had an issue using the --as flag at the end of my command. Kubectl actually still takes it but it doesn't work. It still works immediately after the command though so --as will still work if we move it to after the command.

**Comment by nlopezgi** [comment]
It seems to me there's some agreement about only using the bazel specific `args` parameter combined with `$@`  and placing the flags after the command (but please let me know if I misunderstood). 

If everyone else agrees with that then I think one of you could get started on a PR with the basic functionality (i.e., no tests) and then I can help guide you through how to create tests in a way that does not require duplicating the e2e script.

If that sounds good, then all we need is someone to volunteer to start the PR.

**Comment by omadawn** [comment]
I think we're agreed on args and the location. But I think we need to steer the discussion towards the tests. Both @chrislovecnm and I have PRs in which do the job and could be modified by anyone in seconds to accomplish the change we have agreed upon here. 

But that doesn't accomplish much because the hang up on both of them is tests.

I tried to copy one of the existing e2e tests but when I run in to issues I can't troubleshoot it. It's not a thing I can run them locally without making changes to the code base to point it at my local cluster and to be honest I have no idea what's happening between the bash, python and bazel configs.

It would be nice to add something smaller than a full e2e test which could be run locally.

Anyone know how to write unit tests for Skylark? 

There are some docs here:
https://docs.bazel.build/versions/master/skylark/testing.html
I haven't looked into it. I still thought this was actually python when I created my PR.

**Comment by chrislovecnm** [comment]
@omadawn - @nlopezgi recommend how to modify an e2e test on my PR.

I mentioned this before, IMO your PR should be rebased. 

—-

I think we are in agreement that two use cases should be implemented

1. Include kubectl_args to bazel object (not sure if I using the correct jargon)
2. Include @args as well, so we can send in args via the bazel cli

**Comment by chrislovecnm** [comment]
Another note. This work should be done in s single PR. Merging the two is going to be complex, and this is really a single component of functionality IMO.

@omadawn I can give you permissions to push code changes to my PR if you like.

**Comment by omadawn** [comment]
> @omadawn - @nlopezgi recommend how to modify an e2e test on my PR.
> 
> I mentioned this before, IMO your PR should be rebased.
> 
> —-
> 
> I think we are in agreement that two use cases should be implemented
> 
>     1. Include kubectl_args to bazel object (not sure if I using the correct jargon)
> 
>     2. Include @Args as well, so we can send in args via the bazel cli

Yeah, mine 100% needs to be rebased if we don't delete it. I actually tried that through github but it didn’t work due to permissions (apparently it tries to rebase the copy of my branch within the main repository rather than the one In my repository so that button probably isn’t useful anyway.)

I didn’t want to go through doing it in my fork because we have the two PRs open and I’ve already caused enough confusion by trying to retest it.

If you’re already working on the tests we can do the change from kubectl_args to args in yours. 

Do we want to include kubectl_args? 
I thought we were going with only args and placing $@ after the kubectl command (instead of %{kubectl_args}

I would be happy with both but that might be un-neccessarily complicated.

**Comment by Globegitter** [comment]
@chrislovecnm As @omadawn said I also got the impression we would just go for `args` and leave `kubectl_args` out for now. Also happy to have both options, but what where your thought for having both now?

**Comment by chrislovecnm** [comment]
We need both kubectl_args and args 😊

**Comment by chrislovecnm** [comment]
@nlolezgi fixes the issue setting the kubeconfig location. There are some settings that I want to have all the time, and not just via the bazel cli. What if I have a build where different kubeconfig locations are needed?

**Comment by chrislovecnm** [comment]
I am sure there are some other examples when you would want the flags in the BUILD file as well.

**Comment by omadawn** [comment]
I want most of what I pass to be in the build file.

You _can_ use args in the build file. 

The argument for both might come down to what happens if you have args defined in the BUILD file and you pass args on the command line.

If they add to the existing array of args then having only that one would probably do the job.
If they replace then we actually need both.

I have a vague preference for both even if command line args merges with BUILD file args because then kubectl_args would strictly be limited to _global_ flags and any non-global flags would be passed only on the command line.

**Comment by omadawn** [comment]
O.K. here's a thought. I never tested args on the command line. I replaced kubectl_args with args to allow me to use it in the config. But I had to define it in the object(s) code for that to work.

So here's a question, does $@ work if you have not defined args in the skylark? 

@chrislovecnm you still have kubectl_args defined and in your templates before the kubectl command. Can you test only adding $@ after the kubectl command in in your templates and passing a command line argument? That would give us kubect_args for GLOBAL flags used only in the BUILD file and args only for things passed on the command line.

I can probably try this later today or tomorrow but it will require a bit more of a change and I'm swamped at work today.

**Comment by chrislovecnm** [comment]
@omadawn finally had some free time, and I updated the PR with $@, but still need testing.  Also have not tested $@ on the command line.

**Comment by chrislovecnm** [comment]
@omadawn / @nlopezgi I have implemented the rest of the functionality, and included tests for both using `kubectl_args` in a BUILD file, and passing in argument via the cli on a run command.  

PTLA at https://github.com/bazelbuild/rules_k8s/pull/198

**Comment by nlopezgi** [comment]
created https://github.com/bazelbuild/rules_k8s/pull/224 that enables use of args (no need for kubctl_args) in a way that I think should satisfy everyones use case. Please comment there. Will also close some of the older PRs (only leave @chrislovecnm's one open until we finish up discussion of kubectl_args vs args)

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_k8s/pull/224 is merged in master. Let us know how this works out.

Closing

**Comment by Globegitter** [comment]
Great i will give it s spin.

**Comment by Globegitter** [comment]
I actually forgot that most of our macros use `k8s_objects` under the hood so tested out https://github.com/bazelbuild/rules_k8s/pull/225 and that is working well.

**Comment by xanalogica** [comment]
One position-dependent argument kubectl v1.14.6:
   WORKS:  kubectl newplugincmd --kubeconfig=~/.kube/config1
   FAILS: kubectl --kubeconfig=~/.kube/config1 newplugincmd
