### ISSUE TITLE
document better how to use custom kubernetes version in k8s config

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/rules_k8s#245]
- Provide an example in readme docs
- ideally add an e2e test that pulls a custom version (as a subfolder / subproject in this repo)
- fail early if user does not provide k8s_prefix / k8s_sha256

**Comment by greggdonovan** [comment]
An example for kubectl version 1.10 would be very helpful for us.

**Comment by smukherj1** [comment]
@greggdonovan Documenting how to use a kubectl toolchain where kubectl was built from source in #251.

Unfortunately, v1.10.1 can't be built from source because I get the error mentioned in https://github.com/bazelbuild/rules_k8s/pull/251#issuecomment-448381811

I verified building v1.13.1 from source works. We don't support prebuilt binaries yet.

**Comment by chrislovecnm** [comment]
@greggdonvan we might be able to backport into kubernetes the changes that have been made for 1.13 to fix bazel, or make a branch for Etsy.

@smukherj1 what is the min version that works? Do we have that documented?

**Comment by smukherj1** [comment]
We added a defaults.bzl in the toolchains directory and the documentation points to this as the currently recommended version that is known to work. The documentation of the kubectl_configure function mentions v1.13.0-beta.1 is the minimum version known to work. The example in the docs (being added by my PR) shows it also works with v1.13.1. The documentation says it should work with v1.13.0-beta.1 or later. If not, send us an issue.
