### ISSUE TITLE
Feature request: Only run k8s_objects that have changed

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_k8s#553]
I have a `k8s_objects` target like this:
```
k8s_objects(
    name = "k8s",
    objects = [
        "//packages/kubernetes:defaults",
        "//services/gateway:k8s",
        "//services/consumer:k8s",
        # ...
    ],
)
```
However when I run `bazelisk run //:k8s.apply` it will build and apply all of the specified `objects` every time.

It would be nice if only those objects that have actually changed (or are not yet deployed) will be rebuilt and applied.

**Comment by fejta** [comment]
What is the issue here?

If the objects have not changed since the last time you applied them nothing changes in the cluster. This is one way in which `apply` differs from `replace`.

This matches the behavior outside bazel too:

`kubectl --context=foo apply -f some/dir` will be a noop if all the `some/dir/object.yaml` files are the same as the last time things were applied.
