### ISSUE TITLE
Remove unchanged/useless output from k8s_object

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_k8s#69]
If one does:
```
k8s_robco_object(
  name = "config",
  kind = "configmap",
  template = ":config.yaml",
)
```
you will get a an error (see subject). One can work around it by using `name="x-config"` but that is ugly.

**Comment by mattmoor** [comment]
I changed the title.  Currently this does nothing, so we should just remove it.

**Comment by ensonic** [comment]
I am not sure it is useless. What is the reason for not outputting the expanded yaml file when running build?

**Comment by mattmoor** [comment]
What comes out during the build isn't expanded (pushing wouldn't be hermetic).

Right now it is literally copying the input to the output :)

**Comment by ensonic** [comment]
Yes, the current output is not useful. It would only be useful if it would output a yaml with images resolved. It should be hermetic, since the image would point to the digest.

**Comment by mattmoor** [comment]
Right, and we can only publish the image and produce a resolved template on `bazel run` since that is inherently not hermetic.

**Comment by mattmoor** [comment]
Just to be clear, our hermetic references are to different things :)

What I'm saying is non-hermetic is publishing an image, since it talks to the registry service and accesses things outside of the sandbox like your credential keyring.

The result of `bazel run` (the resolved output) is what I'd call pseudo-hermetic because all of the external references are now content-addresses.  So while it isn't closed per-se, the only way you can successfully deploy it is if get exactly what you intended.
