### ISSUE TITLE
Resolve .yaml files without pulbishing docker images.

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_k8s#98]
Is it possible to get the generated output without deploying the images to an external registry? For k8_object `{name}.yaml` is also not defined.

**Comment by mattmoor** [comment]
I'll give a funny answer: Yes and no, but why?

Yes: if you know which format will be used (e.g. v2.1 vs. v2.2 vs. OCI) and the method in which the image *will* be published, then you can anticipate the image's digest without publishing it.  

No: most of the major public registries support the latest schema (except Quay.io, last I checked), but even with a domain cheat sheet to help you guess, doing this for custom registries is not possible hermetically (e.g. what protocol will `localhost:5000` serve?).

... but why?   I am curious to better understand your use case, but I don't understand the value in having the resolved template without the images published; the resolved references are only useful if they exist.

**Comment by afking** [comment]
So the use case I was looking at was having the build stage in our CI pipeline not depoly the images and without having to rebuild the images (maybe different cache) on a later stage. Closing as your right it doesn't have a strong use case.

**Comment by mattmoor** [comment]
So running: `bazel run :foo > resolved.yaml` to publish the images and capture the resolved template for later deployment (maybe to multiple clusters / namespaces) is kind of how I picture this separation in my mind.

Maybe the first stage only has permission to publish images, and not deploy to Kubernetes.  A later stage with permission to your cluster(s) could then roll out the templates.  Since the templates will generally have all tags resolved to digests, if you combine this with a policy that requires deployment by digest then you have a cryptographic guarantee that the first stage cannot change what's running in production without the later stage's say-so.
